#!/bin/sh
TOKEN=""
SERVER=""
while [ $# -gt 0 ]; do
  case "$1" in
    --token) TOKEN="$2"; shift 2;;
    --server) SERVER="$2"; shift 2;;
    *) shift;;
  esac
done
echo "Rafptor agent (ibmi) started with token $TOKEN server $SERVER"
sleep 3600
