spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/rafptor-test   # overridden by embedded mongo

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.0.4

rafptor:
  security:
    jwt-secret: "test-secret-minimum-32-bytes-long-xxxxxxxxxxxxxxx"
  cors:
    allowed-origins: "http://localhost:4041"
